# action.yml
name: "GitHub Teams Notifications Action"
description: "A GitHub Action that listens to events and sends notifications. Requires secrets.WEBHOOK_URL_PR to be set "
author: "Håvard K. Blixgård, Helse Nord IKT"

outputs:
  response_code:
    description: "Response code from the webhook endpoint"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "zap"
  color: "blue"
