# action.yml
name: "GitHub Notifications Action"
description: "A GitHub Action that listens to events and sends notifications"
author: "Håvard K. Blixgård, Helse Nord IKT"

inputs:
  webhook_url:
    description: "The URL to send pull request data to"
    required: true

outputs:
  response_code:
    description: "Response code from the webhook endpoint"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "zap"
  color: "blue"