# action.yml
name: "GitHub Notifications Action"
description: "A GitHub Action that listens to events and sends notifications"

inputs:
  num:
    description: "Enter a number"
    required: true
    default: "1"

outputs:
  num_squared:
    description: "Square of the input"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "zap"
  color: "blue"