# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch num squared
        id: get_square
        uses: ./ # Uses an action in the root directory
        # or use a released GitHub Action
        # uses: shipyard/github-action/fetch-shipyard-env@1.0.0
        with:
          num: 11

      - name: Display the square of the input number
        run: echo "The square of the number is ${{ steps.get_square.outputs.num_squared }}"